// Generated by CoffeeScript 1.9.3

/* UserScript options {{{1
See http://wiki.greasespot.net/Metadata_Block for more info.

// ==UserScript==
// @name         Lioden Improvements
// @description  Adds various improvements to the game Lioden.
// @namespace    ahto
// @version      0.0
// @include      http://*.lioden.com/*
// @include      http://lioden.com/*
// @require      https://greasyfork.org/scripts/10922-ahto-library/code/Ahto%20Library.js?version=75750
// @grant        none
// ==/UserScript==
 */

/* Features and changes {{{1
General:
- Made the second-to-top bar a little slimmer.

Hunting:
- Automatically reloads flashes the tab when your hunt is finished.
 */
var MAX_PRICE_MAX, gb, gbLink, i, inputBaseName, len, makeHandler, parent, prices, pricesDecor, ref, ref1, sb, sbLink;

MAX_PRICE_MAX = '9999999999';

if (urlMatches(new RegExp('/search_branches\\.php', 'i'))) {
  prices = findMatches('input[name=maxprice]', 1, 1).parent();
  pricesDecor = findMatches('input[name=maxprice2]', 1, 1).parent();
  ref = [[prices, 'maxprice'], [pricesDecor, 'maxprice2']];
  for (i = 0, len = ref.length; i < len; i++) {
    ref1 = ref[i], parent = ref1[0], inputBaseName = ref1[1];
    parent.filter(function() {
      return this.nodeType === 3;
    }).remove();
    sb = parent.children("input[type=text][name=" + inputBaseName + "]");
    gb = parent.children("input[type=text][name=" + inputBaseName + "c]");
    sbLink = sb.after("<a href='javascript:void(0)'> SB</a>");
    gbLink = gb.after("<a href='javascript:void(0)'> GB</a>");
    makeHandler = function(us, them) {
      return function() {
        console.log("Handler called on:", us, "them:", them);
        if (us.val().length) {
          return us.val('');
        } else {
          us.val(MAX_PRICE_MAX);
          return them.val('');
        }
      };
    };
    sbLink.click(makeHandler(sb, gb));
    gbLink.click(makeHandler(gb, sb));
  }
}
